初稿： Translation for docs/core-concepts/events.md
nscript-cn/docs-cn pull request #3
Opened 2017-09-28 15:16 UTC by rexebin

将Jiejiss的翻译搬移到Events分支。

@JieJiSS 请查看docs库的PR上的review修改本分支。

2017-11-19 08:05 UTC, JieJiSS commented
好的

2017-11-19 14:25 UTC, jadertao reviewed
1. 中文英文之间建议加空格。
2. 代码片段中，注释符号"//"后建议空一格。
3. 一些常见单词的统一译法，如Example 1，翻译成什么比较好？ 个人倾向于“示例 1”

2018-02-25 14:27 UTC, JieJiSS commented
我好像git config写错了……那个c141028就是我……非常抱歉
@asnowwolf @rexebin 大佬们帮忙抽空review一下:smile:

2018-06-09 14:50 UTC, XieJiSS requested changes
Still needs approvements.

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +__示例5__ 中的代码片段会在开关（switch）的 checked 值改变时触发 `propertyChange` 事件。
开关 -> 开关控件

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +__示例5__ 中的代码片段会在开关（switch）的 checked 值改变时触发 `propertyChange` 事件。
checked值 -> checked 属性值？

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +### 示例6：创建一个继承自 `Observable` 的类
~~一个~~
类 -> 自定义类

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +__示例6__ 中的代码片段在指定属性的值改变时触发`propertyChange`事件。
属性的->的属性

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +你的业务逻辑可能会需要触发（引发（raise）或发出（emit））一个针对特定操作的自定义事件（参考 __示例7__）。你只需要在该操作完成时调用`Observable.notify()`方法即可实现该目标。这个方法将任意[事件数据接口](http://docs.nativescript.org/api-reference/interfaces/_data_observable_.eventda
触发 ~~（...）~~？

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +你的业务逻辑可能会需要触发（引发（raise）或发出（emit））一个针对特定操作的自定义事件（参考 __示例7__）。你只需要在该操作完成时调用`Observable.notify()`方法即可实现该目标。这个方法将任意[事件数据接口](http://docs.nativescript.org/api-reference/interfaces/_data_observable_.eventda
[事件数据接口] -> [EventData接口]？

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +你的业务逻辑可能会需要触发（引发（raise）或发出（emit））一个针对特定操作的自定义事件（参考 __示例7__）。你只需要在该操作完成时调用`Observable.notify()`方法即可实现该目标。这个方法将任意[事件数据接口](http://docs.nativescript.org/api-reference/interfaces/_data_observable_.eventda
作为 -> 类型为

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +### 示例7：创建自定义事件。
~~。~~

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +下一步就是挂靠到这个事件上：
下一步->随后

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +尽管使用电台做比喻可以方便你理解概念，但是事件在内部实现上更复杂一点。为了能够通知监听器，发送器拥有一个指向监听器的指针。因此即使你将监听器对象设置为 `null` 或者 `undefined` ，由于仍存活的发送器中有对它的引用，它也不符合垃圾回收器的回收条件。当发送器和监听器的生命周期相差很大时，将会导致内存泄漏。
电台->广播电台

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +尽管使用电台做比喻可以方便你理解概念，但是事件在内部实现上更复杂一点。为了能够通知监听器，发送器拥有一个指向监听器的指针。因此即使你将监听器对象设置为 `null` 或者 `undefined` ，由于仍存活的发送器中有对它的引用，它也不符合垃圾回收器的回收条件。当发送器和监听器的生命周期相差很大时，将会导致内存泄漏。
方便 ~~你~~ 理解 ~~概念~~，……

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +尽管使用电台做比喻可以方便你理解概念，但是事件在内部实现上更复杂一点。为了能够通知监听器，发送器拥有一个指向监听器的指针。因此即使你将监听器对象设置为 `null` 或者 `undefined` ，由于仍存活的发送器中有对它的引用，它也不符合垃圾回收器的回收条件。当发送器和监听器的生命周期相差很大时，将会导致内存泄漏。
但是 -> 然而

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +尽管使用电台做比喻可以方便你理解概念，但是事件在内部实现上更复杂一点。为了能够通知监听器，发送器拥有一个指向监听器的指针。因此即使你将监听器对象设置为 `null` 或者 `undefined` ，由于仍存活的发送器中有对它的引用，它也不符合垃圾回收器的回收条件。当发送器和监听器的生命周期相差很大时，将会导致内存泄漏。
拥有->有

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +尽管使用电台做比喻可以方便你理解概念，但是事件在内部实现上更复杂一点。为了能够通知监听器，发送器拥有一个指向监听器的指针。因此即使你将监听器对象设置为 `null` 或者 `undefined` ，由于仍存活的发送器中有对它的引用，它也不符合垃圾回收器的回收条件。当发送器和监听器的生命周期相差很大时，将会导致内存泄漏。
它也不符合 -> 所以它不符合

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +尽管使用电台做比喻可以方便你理解概念，但是事件在内部实现上更复杂一点。为了能够通知监听器，发送器拥有一个指向监听器的指针。因此即使你将监听器对象设置为 `null` 或者 `undefined` ，由于仍存活的发送器中有对它的引用，它也不符合垃圾回收器的回收条件。当发送器和监听器的生命周期相差很大时，将会导致内存泄漏。
垃圾回收 ~~器的回收~~ 的

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +尽管使用电台做比喻可以方便你理解概念，但是事件在内部实现上更复杂一点。为了能够通知监听器，发送器拥有一个指向监听器的指针。因此即使你将监听器对象设置为 `null` 或者 `undefined` ，由于仍存活的发送器中有对它的引用，它也不符合垃圾回收器的回收条件。当发送器和监听器的生命周期相差很大时，将会导致内存泄漏。
当……时，->所以……

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +设想这样一种场景：一个 UI 元素创建了许多子控件，每个控件都挂靠到了父元素的一个事件上。随后，有一个子控件被释放了（比如，在列表视图（list view）的滚动期间），于是导致了内存泄漏。
比如，->也许是？

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +为了防止这种内存泄漏，在释放监听器对象之前移除事件监听处理器是个不错的办法。不幸的是，有时你无法决定确切的调用 `off` 或者 `removeEventListener` 函数的时机。在这种情况下，使用 NativeScript 框架提供的另一种选项：*弱事件（weak events）*。
不幸的是 -> 然而
太翻译腔了

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +为了防止这种内存泄漏，在释放监听器对象之前移除事件监听处理器是个不错的办法。不幸的是，有时你无法决定确切的调用 `off` 或者 `removeEventListener` 函数的时机。在这种情况下，使用 NativeScript 框架提供的另一种选项：*弱事件（weak events）*。
使用 -> 可以使用

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +## 使用弱事件
如何使用弱事件？

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +弱事件监听器的用法和普通事件的很像。__示例8__ 展示如何增加一个弱事件监听器（引入了使代码更清楚的注释）：
引入 -> 添加

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +### 示例8：创造一个弱事件并处理一个属性改变（property change）事件
~~一个~~

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +  // 创建一个到事件监听器对象的弱引用
~~一个~~

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +  // 创建一个到事件监听器对象的弱引用
下同

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +__示例8__ 展示了如何将一个弱事件监听器附着到一个可观测对象（observable object）的实例。仔细浏览 `handlePropertyChange` 函数便会发现 `this` 对象的 `text` 属性在 `propertyChange` 事件（通过按钮触摸事件）触发时被改变了。该函数示范了如何使用 `handlerContext` 属性&mdash;该属性的值在事件处理器函数
~~一个~~

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +__示例8__ 展示了如何将一个弱事件监听器附着到一个可观测对象（observable object）的实例。仔细浏览 `handlePropertyChange` 函数便会发现 `this` 对象的 `text` 属性在 `propertyChange` 事件（通过按钮触摸事件）触发时被改变了。该函数示范了如何使用 `handlerContext` 属性&mdash;该属性的值在事件处理器函数
浏览->观察

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +`targetWeakRef` 和 `key` 属性在对于某一事件调用（invoke）函数时是可选的。然而，它们允许你移除事件监听器。这些属性被用作储存弱类型监听器的键-值对的键名。
在对于->当

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +`targetWeakRef` 和 `key` 属性在对于某一事件调用（invoke）函数时是可选的。然而，它们允许你移除事件监听器。这些属性被用作储存弱类型监听器的键-值对的键名。
它们允许你->通过使用它们可以

2018-06-09 14:50 UTC, JieJiSS commented on docs/core-concepts/events.md
> +`targetWeakRef` 和 `key` 属性在对于某一事件调用（invoke）函数时是可选的。然而，它们允许你移除事件监听器。这些属性被用作储存弱类型监听器的键-值对的键名。
属性->属性值将

2018-06-10 02:18 UTC, merged